remote_theme: pages-themes/slate@v0.2.0
title: [Welcome!]
description: [Explore the personal portfolio of a dedicated Data Science graduate student.
For more information on the project, you could simply click its title. :)] 
